project:
  type: website
  output-dir: docs

website:
  title: "pet estatistica"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    lang: pt

editor: visual

